name: NPM Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Use Node.js v16
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.yarnpkg.com/

      - name: Install Dependencies
        run: |
          yarn --immutable

      - name: Build Library
        run: yarn build:lib

      - name: Copy README
        run: cp README.md ./dist/ngx-smooth-dnd/

      - name: Publish
        run: |
          for d in dist/*; do
            pushd $d

            npm publish

            popd
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
